import TendenceCentrale_Variabilite
import AnalyseCombinatoire


print('-----------------------------------------------------------')
data_input = input("Entrez les éléments séparés par des espaces : ")
Data = list(map(int, data_input.split())) 
print("Data")
print(Data)
print("Sorted Data")
print(sorted(Data))
print("La moyenne = ",TendenceCentrale_Variabilite.Moyenne(Data))
print("La mediane = " ,TendenceCentrale_Variabilite.Mediane(Data))
print("Le mode" , *TendenceCentrale_Variabilite.Mode(Data))
print("La variance" , TendenceCentrale_Variabilite.Variance(Data))
print("L'Ecart-Type" , TendenceCentrale_Variabilite.EcartType(Data))
print("L'Etendu" , TendenceCentrale_Variabilite.Etendu(Data))
print('-----------------------------------------------------------')
# print("-> calcule la puissance")
# nbr = int(input("Entre un nombre : "))
# puissance = int(input("Entre la puissance : "))
# print("la puissance = " , AnalyseCombinatoire.puissance(nbr,puissance))
print("-> calcule de factoriel")
nbr = int(input("Entre un nombre : "))
print("factoriel = " , AnalyseCombinatoire.factoriel(nbr))
print("-> calcule de Combinaison")
r = int(input("Entre  r : "))
n = int(input("Entre n : "))
print("combinaison = " , AnalyseCombinatoire.combinaison(n,r))
