import Cours1_TendenceCentrale_Variabilite
import Cours2_AnalyseCombinatoire


print('-----------------------------------------------------------')
data_input = input("Entrez les éléments séparés par des espaces : ")
Data = list(map(int, data_input.split())) 
print("Data")
print(Data)
print("Sorted Data")
print(sorted(Data))
print("La moyenne = ",Cours1_TendenceCentrale_Variabilite.Moyenne(Data))
print("La mediane = " ,Cours1_TendenceCentrale_Variabilite.Mediane(Data))
print("Le mode" , *Cours1_TendenceCentrale_Variabilite.Mode(Data))
print("La variance" , Cours1_TendenceCentrale_Variabilite.Variance(Data))
print("L'Ecart-Type" , Cours1_TendenceCentrale_Variabilite.EcartType(Data))
print("L'Etendu" , Cours1_TendenceCentrale_Variabilite.Etendu(Data))
print('-----------------------------------------------------------')
# print("-> calcule la puissance")
# nbr = int(input("Entre un nombre : "))
# puissance = int(input("Entre la puissance : "))
# print("la puissance = " , AnalyseCombinatoire.puissance(nbr,puissance))
print("-> calcule de factoriel")
nbr = int(input("Entre un nombre : "))
print("factoriel = " , Cours2_AnalyseCombinatoire.factoriel(nbr))
print("-> calcule de Combinaison")
r = int(input("Entre  r : "))
n = int(input("Entre n : "))
print("combinaison = " , Cours2_AnalyseCombinatoire.combinaison(n,r))
